version: 2.1

orbs:
  docker: circleci/docker@0.5.13
  heroku: circleci/heroku@0.0.10

jobs:
  run_tests:
    working_directory: ~/react-app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  heroku_deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a leboncoin-demo web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a leboncoin-demo web

workflows:
  version: 2
  build_deploy:
    jobs:
      - run_tests
      - heroku_deploy
