version: 2.1

orbs:
  docker: circleci/docker@0.5.13
  heroku: circleci/heroku@x.y

jobs:
  run_tests:
    working_directory: ~/react-app
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  heroku/deploy-via-git:
    requires:
      - build # only run deploy-via-git job if the build job has completed
    filters:
      branches:
        only: master

        workflows:
          heroku_deploy:
            jobs:
              - build
              - heroku/deploy-via-git:
                  requires:
                    - build # only run deploy-via-git job if the build job has completed
                  filters:
                    branches:
                      only: master
workflows:
  version: 2
  build_deploy:
    jobs:
      - run_tests
      - heroku/deploy-via-git
